# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19eacb4c4e856551d7db15a3a2e16bebf02ccb00e517c6ff98a1e364962d8ea8c997d1ac8099a0cf99947c0229fa90227c9d38837999a3a8f57d24630e3a8c59

test:
  secret_key_base: 1a58d10449fd158866cf075e1a86349f7126e934aa7b9c3f77da0d166eede9ace97d264ae5e95d7fae1e54b05d07ce0e7c8e40e4f662ab8618424225a472ace6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
